### ISSUE TITLE
playable dark tribe and settlers4 history edition

### ISSUE THREAD

**Issue by lstolcman** [PaweX/NewSettlers4Project#1]
Hi

I don't know if you know, but BlueByte/ubisoft released "refreshed" settlers (from 1 to 7), with hd graphics and playable multiplayer:
https://www.ubisoft.com/pl-pl/game/the-settlers-history-collection
https://www.gry-online.pl/gry/the-settlers-history-collection/zc55a1

About dark tribe, [here](http://www.thesettlers4mods.vhn.pl/viewtopic.php?id=18) someone created a working mod. I couldn't find any github for this though :(

I am interested in improving the game, however if Bluebyte will fix all the bugs in history collection, there's no point to do that again "hard way" in assembly. I'd be better to do some extra modifications in game, e.g. how market works, how pioneers works and so on

**Comment by PaweX** [comment]
According to my knowledge. New edition of The Settlers IV (History Edition) improves just graphics. Nothing else. Ubisoft even didn't translate Neue Welt into English.
I made a tool to translate/edit language files of the game. It's available on my blog. I am planning to translate the whole game into Polish (Neue Welt and and Community pack).

**Comment by lstolcman** [comment]
I "translated" settlers 4 history collection to polish by copying translated file from old version. It works, however the font has some glitches (no polish characters). It could be possible to do full translation (videos, map descriptions etc).


Could you share a link to your blog?

**Comment by PaweX** [comment]
Yes, it's on my github profile. Here is Polish version: https://pawex3-pl.blogspot.com/2019/01/the-settlers-iv-game-translation-tool.html - for my tool.

I planned to make translation of S4 The New World addition and then share it.
Here is the GitHub project page for sharing translations of The Settlers IV:
https://github.com/PaweX/Settlers_IV_Language_Translations

**Comment by PaweX** [comment]
@lstolcman how do you set Polish in Settlers IV HE without replacing it with English, German or French? Is it somewhere in the Win registry? Or you just replaced?

**Comment by lstolcman** [comment]
@PaweX I renamed a file in `txt` directory. `s4_texts.dat0` is english, the others are other languages (polish is located in `s4_texts.dat5`). You need to rename `s4_texts.dat5` to `s4_texts.dat0` and it works. There are some glitches though, e.g. polish characters are not rendered correctly

**Comment by PaweX** [comment]
I am looking for a way to load Polish language from s4_texts.dat5. But I have no idea where in HE language settings are stored.
